[env:esp32dev]
platform = espressif32
; board = esp32dev
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
board_build.partitions = noota4.csv
