[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 4MB
board_build.partitions = default.csv
build_flags = 
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
; lib_deps = ivanseidel/LinkedList@0.0.0-alpha+sha.dac3874d28

; https://community.platformio.org/t/need-help-add-esp32-s3-mini-in-platform-io-in-vs-code/26041/2
; https://community.platformio.org/t/esp32-s3-zero-does-not-work-on-platformio/40297/9
